[package]
name = "eg-eval"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
eg-model.workspace = true
rustc-hash.workspace = true
serde.workspace = true

[dev-dependencies]
eg-ingest.workspace = true
