[package]
name = "eg-index"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
eg-model.workspace = true
petgraph.workspace = true
eg-graph.workspace = true
rustc-hash.workspace = true
serde.workspace = true
tantivy.workspace = true
thiserror.workspace = true

[dev-dependencies]
eg-ingest.workspace = true
tantivy.workspace = true
